import type { Metadata } from 'next';
import './globals.css';
import { Roboto, Noto_Sans_KR, Oranienbaum } from 'next/font/google'; // Roboto와 한글 NotoSans를 사용합니다.
import Theme from '@/components/Theme';
import { ThemeProvider } from 'next-themes';

const notoSansKr = Noto_Sans_KR({
  preload: false,
  weight: ['100', '400', '700', '900'], // 가변 폰트가 아닌 경우, 사용할 fontWeight 배열
  variable: '--sans', // CSS 변수 방식으로 스타일을 지정할 경우에 사용합니다.
});
const oranienbaum = Oranienbaum({
  subsets: ['latin'],
  weight: '400',
  variable: '--oranienbaum', // CSS 변수 방식으로 스타일을 지정할 경우에 사용합니다.
});

const roboto = Roboto({
  subsets: ['latin'], // preload에 사용할 subsets입니다.
  weight: ['100', '400', '700'],
  variable: '--roboto', // CSS 변수 방식으로 스타일을 지정할 경우에 사용합니다.
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='scrollbar-hide' suppressHydrationWarning>
      <body className={`${[notoSansKr.variable, roboto.variable, oranienbaum.variable].join(' ')} font-notosans`}>
        <ThemeProvider storageKey='hunmok-theme' defaultTheme='system' value={{ dark: 'dracula', light: 'emerald' }}>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
