import type { Metadata } from 'next';
import './globals.css';
import 'react-notion-x/src/styles.css';
import 'prismjs/themes/prism-tomorrow.css';
import 'katex/dist/katex.min.css';

import { Roboto, Noto_Sans_KR, Oranienbaum, IBM_Plex_Sans_KR } from 'next/font/google'; // Roboto와 한글 NotoSans를 사용합니다.

import { ThemeProvider } from 'next-themes';
import { ReactQueryClientProvider } from '@/components/common/ReactQueryClientProvider';
import Footer from '@/components/Footer';
import NavBar from '@/components/NavBar';

const notoSansKr = Noto_Sans_KR({
  preload: false,
  weight: ['100', '400', '700', '900'], // 가변 폰트가 아닌 경우, 사용할 fontWeight 배열
  variable: '--sans',
});
const oranienbaum = Oranienbaum({
  subsets: ['latin'],
  weight: '400',
  variable: '--oranienbaum',
});

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100', '400', '700'],
  variable: '--roboto',
});
const ibmSans = IBM_Plex_Sans_KR({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--ibm-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang='ko' className='scrollbar-hide sm:scrollbar-default' suppressHydrationWarning>
        <body
          className={`${[notoSansKr.variable, roboto.variable, oranienbaum.variable, ibmSans.variable].join(
            ' '
          )} font-sans`}
        >
          <ThemeProvider
            storageKey='hunmok-theme'
            defaultTheme='system'
            value={{ lighten: 'emerald', light: 'garden', dark: 'dim', darken: 'night' }}
          >
            <Container>
              <NavBar />

              {children}
              <Footer />
            </Container>
          </ThemeProvider>
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}

function Container({ children }: any) {
  return (
    <div className='flex justify-center w-full bg-base-200'>
      <div className='max-w-5xl w-full bg-base-100 shadow-lg'>{children}</div>
    </div>
  );
}
